### ISSUE TITLE
为 Paddle Toolbox 添加 Activation

### ISSUE THREAD

**Issue by SigureMo** [cattidea/paddle-toolbox#1]
## 任务详情

Paddle Toolbox 是为大家提供一些易用且常用功能的工具箱，但由于尚处于早期开发阶段，所以在功能性上尚不完善。

Paddle Toolbox 目前在功能和 API 设计上参考了 [Torch Toolbox](https://github.com/PistonY/torch-toolbox) 的设计理念，将补充的 API 路径尽可能的贴合了框架（PyTorch）本身的 API 结构，因此 Paddle Toolbox 补充的 API 也应当尽可能地贴合 PaddlePaddle 相应功能的 API 路径。

本任务需要实现类似于 tf.keras.layers.Activation 的功能，为用户提供 pptb.nn.Activation 这一 API，该 API 可以直接接收激活函数类型的字符串参数，如 pptb.nn.Activation('relu') 即对应了 ReLU 激活函数，实现方式可以参考 Torch Toolbox 相应部分。

## 任务属性

- 难度：⭐️
- 前置任务：无
- 任务序号：4

## 技术要求

- 熟悉 Python
- 了解 tf.keras.layers.Activation 功能
- 了解 Paddle 高层 API 使用方式以及自定义激活函数方式

## 需完成内容

- 通过 pptb.nn.Activation 能够正确调用该功能
- 文档（README）
- 单元测试

以上内容以 PR 形式提交

## 参考链接

- [tf.keras.layers.Activation 文档](https://tensorflow.google.cn/api_docs/python/tf/keras/layers/Activation)
- [Torch Toolbox](https://github.com/PistonY/torch-toolbox)

**Comment by Ainavo** [comment]
【状态】：报名

**Comment by SigureMo** [comment]
๑乛ᆺ乛๑!!!
